# Generated by Django 5.2.7 on 2025-10-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_kana', models.CharField(max_length=100)),
                ('title_english', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('release_date', models.DateField()),
                ('release_price', models.IntegerField()),
                ('loose_price', models.IntegerField()),
                ('boxed_price', models.IntegerField()),
            ],
        ),
    ]
